// Nigerian States and Cities Data Helper
class NigerianLocations {
  static const Map<String, List<String>> statesWithCities = {
    'Abia': [
      'Aba',
      'Umuahia',
      'Arochukwu',
      'Ohafia',
      'Isiala Ngwa',
      'Osisioma',
      'Ugwunagbo',
      'Ukwa',
    ],
    'Adamawa': [
      'Yola',
      'Mubi',
      'Jimeta',
      'Numan',
      'Ganye',
      'Gombi',
      'Hong',
    ],
    'Akwa Ibom': [
      'Uyo',
      'Eket',
      'Ikot Ekpene',
      'Oron',
      'Abak',
      'Etinan',
      'Ikot Abasi',
    ],
    'Anambra': [
      'Awka',
      'Onitsha',
      'Nnewi',
      'Ekwulobia',
      'Agulu',
      'Nkpor',
      'Ogidi',
      'Ihiala',
    ],
    'Bauchi': [
      'Bauchi',
      'Azare',
      'Misau',
      'Jama\'are',
      'Katagum',
      'Ningi',
    ],
    'Bayelsa': [
      'Yenagoa',
      'Brass',
      'Sagbama',
      'Ekeremor',
      'Ogbia',
      'Nembe',
    ],
    'Benue': [
      'Makurdi',
      'Gboko',
      'Otukpo',
      'Katsina-Ala',
      'Adikpo',
      'Vandeikya',
    ],
    'Borno': [
      'Maiduguri',
      'Biu',
      'Bama',
      'Dikwa',
      'Monguno',
      'Damboa',
    ],
    'Cross River': [
      'Calabar',
      'Ugep',
      'Ikom',
      'Ogoja',
      'Obudu',
      'Akamkpa',
    ],
    'Delta': [
      'Asaba',
      'Warri',
      'Sapele',
      'Ughelli',
      'Agbor',
      'Kwale',
      'Ozoro',
      'Oleh',
    ],
    'Ebonyi': [
      'Abakaliki',
      'Afikpo',
      'Onueke',
      'Ezza',
      'Ishielu',
    ],
    'Edo': [
      'Benin City',
      'Auchi',
      'Ekpoma',
      'Uromi',
      'Irrua',
      'Ubiaja',
      'Igueben',
    ],
    'Ekiti': [
      'Ado-Ekiti',
      'Ikere',
      'Aramoko',
      'Ijero',
      'Emure',
      'Ise',
    ],
    'Enugu': [
      'Enugu',
      'Nsukka',
      'Agbani',
      'Awgu',
      'Oji River',
      'Udi',
      'Ezeagu',
    ],
    'Gombe': [
      'Gombe',
      'Kumo',
      'Deba',
      'Bajoga',
      'Kaltungo',
    ],
    'Imo': [
      'Owerri',
      'Orlu',
      'Okigwe',
      'Oguta',
      'Mbaise',
      'Nkwerre',
      'Mbaitoli',
    ],
    'Jigawa': [
      'Dutse',
      'Hadejia',
      'Gumel',
      'Kazaure',
      'Ringim',
      'Birnin Kudu',
    ],
    'Kaduna': [
      'Kaduna',
      'Zaria',
      'Kafanchan',
      'Kagoro',
      'Saminaka',
      'Makarfi',
    ],
    'Kano': [
      'Kano',
      'Wudil',
      'Gwarzo',
      'Bichi',
      'Rano',
      'Gaya',
    ],
    'Katsina': [
      'Katsina',
      'Daura',
      'Funtua',
      'Malumfashi',
      'Dutsin-Ma',
      'Kankia',
    ],
    'Kebbi': [
      'Birnin Kebbi',
      'Argungu',
      'Zuru',
      'Yauri',
      'Jega',
    ],
    'Kogi': [
      'Lokoja',
      'Okene',
      'Idah',
      'Kabba',
      'Ankpa',
      'Ajaokuta',
    ],
    'Kwara': [
      'Ilorin',
      'Offa',
      'Jebba',
      'Omu-Aran',
      'Lafiagi',
      'Pategi',
    ],
    'Lagos': [
      'Ikeja',
      'Lekki',
      'Victoria Island',
      'Ikoyi',
      'Ajah',
      'Surulere',
      'Yaba',
      'Maryland',
      'Magodo',
      'Gbagada',
      'Apapa',
      'Festac',
      'Ikorodu',
      'Epe',
      'Badagry',
      'Alimosho',
      'Oshodi',
      'Mushin',
      'Isolo',
      'Ejigbo',
      'Agege',
      'Ifako-Ijaiye',
      'Somolu',
      'Kosofe',
      'Eti-Osa',
      'Amuwo-Odofin',
    ],
    'Nasarawa': [
      'Lafia',
      'Keffi',
      'Akwanga',
      'Nasarawa',
      'Doma',
    ],
    'Niger': [
      'Minna',
      'Bida',
      'Kontagora',
      'Suleja',
      'Mokwa',
      'New Bussa',
    ],
    'Ogun': [
      'Abeokuta',
      'Ijebu Ode',
      'Sagamu',
      'Ilaro',
      'Ota',
      'Sango Ota',
      'Ifo',
      'Agbara',
      'Mowe',
      'Ibafo',
    ],
    'Ondo': [
      'Akure',
      'Ondo',
      'Owo',
      'Ore',
      'Ikare',
      'Okitipupa',
    ],
    'Osun': [
      'Osogbo',
      'Ile-Ife',
      'Ilesa',
      'Ede',
      'Iwo',
      'Ikirun',
      'Ejigbo',
    ],
    'Oyo': [
      'Ibadan',
      'Ogbomoso',
      'Oyo',
      'Iseyin',
      'Saki',
      'Igbo-Ora',
      'Eruwa',
      'Ibarapa',
    ],
    'Plateau': [
      'Jos',
      'Bukuru',
      'Pankshin',
      'Shendam',
      'Wase',
      'Langtang',
    ],
    'Rivers': [
      'Port Harcourt',
      'Obio-Akpor',
      'Eleme',
      'Bonny',
      'Degema',
      'Okrika',
      'Omoku',
      'Ahoada',
      'Rumuokoro',
      'GRA',
      'Trans Amadi',
      'Woji',
      'Rumuola',
      'Choba',
    ],
    'Sokoto': [
      'Sokoto',
      'Gwadabawa',
      'Tambuwal',
      'Wurno',
      'Bodinga',
    ],
    'Taraba': [
      'Jalingo',
      'Wukari',
      'Bali',
      'Mutum Biyu',
      'Gembu',
    ],
    'Yobe': [
      'Damaturu',
      'Potiskum',
      'Gashua',
      'Nguru',
      'Geidam',
    ],
    'Zamfara': [
      'Gusau',
      'Kaura Namoda',
      'Talata Mafara',
      'Anka',
      'Bungudu',
    ],
    'FCT': [
      'Abuja',
      'Gwagwalada',
      'Kubwa',
      'Kuje',
      'Bwari',
      'Nyanya',
      'Lugbe',
      'Maitama',
      'Asokoro',
      'Garki',
      'Wuse',
      'Gwarinpa',
      'Lokogoma',
      'Apo',
      'Utako',
      'Jabi',
      'Kado',
      'Lifecamp',
      'Durumi',
      'Katampe',
    ],
  };

  static List<String> getAllStates() {
    return statesWithCities.keys.toList()..sort();
  }

  static List<String> getCitiesForState(String state) {
    return statesWithCities[state] ?? [];
  }

  static bool isValidState(String state) {
    return statesWithCities.containsKey(state);
  }

  static bool isValidCity(String state, String city) {
    final cities = statesWithCities[state];
    if (cities == null) return false;
    return cities.contains(city);
  }
}